### ISSUE TITLE
The lock doesn't seem to wait for the tasks inside the sync to complete.

### ISSUE THREAD

**Issue by jdevp** [tekartik/synchronized.dart#16]
I have following code snippet but it doesn't seem to work as described by the package or something that I did wrong.

initState() {
   Toolkit.list2File2();
    print("This should print out after file names");
}

In my Toolkit file. I have the following for list2File2 function

static list2File2() async {
    List files = new List();
    var lock = new Lock();
    await lock.synchronized(() async {
      String directory = (await getApplicationDocumentsDirectory()).path;
      files = Directory("$directory").listSync();
         for (FileSystemEntity f in files) {
           print(f.path);
      }
    });
}

If the package works correctly, I would expect that the file names get printed out first before the "print" statement in initState but it doesn't work that way.

**Comment by alextekartik** [comment]
You should either do:

```dart
await Toolkit.list2File2();
print("This should print out after file names");
```

or (assuming you extract the lock object)
```dart
Toolkit.list2File2();
lock.synchronized(() {
   print("This should print out after file names");
});

```
