### ISSUE TITLE
fluttertoast-8.0 Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type View?

### ISSUE THREAD

**Issue by xiaorenzi** [tekartik/synchronized.dart#17]
fluttertoast-8.0 kotlin complite failure

../.pub-cache/hosted/pub.flutter-io.cn/fluttertoast-8.0.5/android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/MethodCallHandlerImpl.kt: (129, 28): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type View?

**Comment by alextekartik** [comment]
This issues tab is about issues regarding the synchronized package. You might want to fill an issue on fluttertoast here: https://github.com/PonnamKarthik/FlutterToast
