### ISSUE TITLE
Dart 2 support

### ISSUE THREAD

**Issue by renefloor** [tekartik/synchronized.dart#2]
Hi,

I am not sure if this is an issue or things I did wrong myself.
I have code like this and used the synchronized method to make sure only 1 instance is made:
```
  static CacheManager _instance;
  static Future<CacheManager> getInstance() async {
    if (_instance == null) {
      await synchronized(_lock, () async {
        if (_instance == null) {
          _instance = new CacheManager._();
          await _instance._init();
        }
      });
    }
    return _instance;
  }
```

However, it looks like all calls to this method directly go inside the synchronized. I know Dart 2 changed how Futures work:

> Note for Dart 2: There is a slight breaking change for async in Dart 2. Instead of immediately suspending, async functions execute synchronously until the first await. In most cases, you won’t notice a change in behavior—as long as you await each time you call an async method, it won’t be an issue.

Could it be that this packages is broken when using Dart 2, or do I use this package wrongly.

**Comment by alextekartik** [comment]
Hi and thanks for the report. For me it looks fine. The dart2 changes should affect the timing (and some tests around the timing) but not (in theory) the behavior.
When you say that it goes inside, do you mean that the "block" is executed in parallel, i.e. if I add some print (and some slight change on how I would do it, using a Lock object), you get an "init start" twice before getting an "init end"?
```dart
  static final _lock = new Lock();
  static CacheManager _instance;
  static Future<CacheManager> getInstance() async {
    if (_instance == null) {
      await _lock.synchronized(() async {
        print("init start");
        if (_instance == null) {
          _instance = new CacheManager._();
          await _instance._init();
        }
        print("init end");
      });
    }
    return _instance;
  }
```

**Comment by renefloor** [comment]
You are right. With added logging everything seems to be alright. Maybe it was the debugger that was messing with things or there was something else wrong..
