### ISSUE TITLE
we cant manually unlock function lock.synchronized

### ISSUE THREAD

**Issue by divyaEncodework** [tekartik/synchronized.dart#24]
can you please guide for how i can unlock function manually after locking?
because in one function my while database gets locked and not any data displayed in my app.

**Comment by alextekartik** [comment]
Hi and sorry for the poor documentation. This is similar to the `synchronized` java keyword. Unless you exit the _synchronized_ function (or throw an exception) the lock remain locked. If indeed during your function gets locked there is nothing much you can besides handling it yourself (it if is ok to get locked - but well in general it should not be ok -, you could add a timeout - not in the synchronized call but in you action:

```dart
await lock.synchronized(() async {
  await () async {
    // .. call to function that might lock
  } ().timeout(Duration(milliseconds: 500)); // Don't lock more than 500ms
});
```

**Comment by divyaEncodework** [comment]
okay, thank you.
