### ISSUE TITLE
If the lock call function contains await inside, the lock is invalid

### ISSUE THREAD

**Issue by tolzlz** [tekartik/synchronized.dart#28]
```
Future writeSlow(int value) async  {
  // await Future.delayed(new Duration(milliseconds: 1));
  print("writeSlow:::"+value.toString());
}
Future write(List<int> values) async {
  for (int value in values) {
    await writeSlow(value);
  }
}
Future write1234() async {
  Lock lock = Lock(reentrant: true);
  lock.synchronized(() async {
    write([1, 2, 3, 4]);
  });
}

void  main(){
  write1234();
  write1234();
}
```

output:

I/flutter (23920): writeSlow:::1
I/flutter (23920): writeSlow:::1
I/flutter (23920): writeSlow:::2
I/flutter (23920): writeSlow:::2
I/flutter (23920): writeSlow:::3
I/flutter (23920): writeSlow:::3
I/flutter (23920): writeSlow:::4
I/flutter (23920): writeSlow:::4

If await is added before writeSlow calls the method, the lock effect will be invalid

**Comment by alextekartik** [comment]
I can spot 2 mistakes:
- There should be a single Lock instance for the code you want to be synchronized, here a new lock is created each time in write1234.
- In the synchronized method you need to add await (i.e. the awaited block will be synchronized).

write1234 can be fixed in the following way:
```dart
// There should be a single lock instance in this case
Lock lock = Lock(reentrant: true);

Future write1234() async {
  lock.synchronized(() async {
    // Important to add await here.
    await write([1, 2, 3, 4]);
  });
}
```

**Comment by tolzlz** [comment]
> 我可以发现 2 个错误：
> 
> * 您要同步的代码应该有一个 Lock 实例，这里每次在 write1234 中都会创建一个新锁。
> * 在 synchronized 方法中你需要添加 await （即等待的块将被同步）。
> 
> write1234 可以通过以下方式修复：
> 
> ```dart
> // There should be a single lock instance in this case
> Lock lock = Lock(reentrant: true);
> 
> Future write1234() async {
>   lock.synchronized(() async {
>     // Important to add await here.
>     await write([1, 2, 3, 4]);
>   });
> }
> ```

thinks
